In [ ]:
# 1.1 Upload dataset
from google.colab import files
uploaded = files.upload()

Saving MSCA 691 Winter 2026 Exam - Classification data.xlsx to MSCA 691 Winter 2026 Exam - Classification data.xlsx


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


# **Explore**

**Explore**

In [ ]:
df = pd.read_excel("MSCA 691 Winter 2026 Exam - Classification data.xlsx")
df.head(10)

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
0,0.123834,9.297480,1.498766,0.323220,1.999864,2.049911,2.134822,2.281462,2.469366,0.207325,...,-664.089768,-61.964615,-31.128375,-10.889777,-6.514377,-4.035811,-3.055236,-2.457894,-2.106336,2
1,0.052498,10.885088,1.507536,0.326396,0.137770,0.208951,0.346292,0.675091,1.508829,0.254048,...,-3232.163144,-38.910010,-326.170815,-29.350689,-93.519481,-17.455662,-37.966592,-10.278538,-18.253635,1
2,0.076550,10.577796,1.495518,0.327111,0.970216,1.024977,1.117131,1.301515,1.645524,0.244901,...,-2581.474052,-280.343734,-263.145766,-92.787279,-76.752471,-39.469282,-31.441637,-19.331588,-15.258128,2
3,0.154461,7.406575,1.375521,0.291584,0.647427,0.706091,0.802205,1.002346,1.752694,0.355455,...,-119.612150,-9.571032,-6.836118,-4.975731,-3.982816,-3.318144,-2.844132,-2.488609,-2.212097,2
4,0.086716,10.021554,1.467074,0.377824,1.784227,1.814548,1.865944,1.984767,2.467012,0.140866,...,-1333.815007,-58.625966,-53.657188,-11.532631,-8.533754,-4.279640,-3.395205,-2.571013,-2.218998,2
5,0.126274,9.879296,1.469167,0.317264,3.277643,3.314871,3.378884,3.450732,3.491603,0.206501,...,-1477.372496,-224.820800,-139.084197,-67.068808,-44.358774,-28.093988,-19.758335,-13.914378,-10.264698,2
6,0.156449,8.814764,1.430906,0.264672,-0.095314,-0.008857,0.146006,0.495518,1.689912,0.377183,...,-618.496050,-60.335300,-23.012685,-8.995326,-5.236924,-3.628765,-2.865312,-2.412898,-2.108944,2
7,0.064881,9.995979,1.407055,0.307897,2.248317,2.290393,2.360460,2.502160,2.821723,0.284700,...,-1206.366595,-86.926207,-52.723380,-14.802198,-8.833185,-4.713788,-3.402941,-2.576087,-2.157639,2
8,0.128994,7.936444,1.341568,0.220187,1.083813,1.146291,1.236575,1.375157,1.668463,0.498892,...,-478.908297,-0.849046,-12.931896,-3.975019,-3.826358,-2.931048,-2.551254,-2.217033,-1.973258,2
9,0.080290,10.580593,1.454688,0.369858,0.439048,0.484813,0.570551,0.764303,1.186946,0.193346,...,-2460.859861,-119.537799,-128.515979,-24.595218,-18.434060,-7.151861,-5.175103,-3.260102,-2.616345,2


In [ ]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171 entries, 0 to 170
Data columns (total 24 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X1      171 non-null    float64
 1   X2      171 non-null    float64
 2   X3      171 non-null    float64
 3   X4      171 non-null    float64
 4   X5      171 non-null    float64
 5   X6      171 non-null    float64
 6   X7      171 non-null    float64
 7   X8      171 non-null    float64
 8   X9      171 non-null    float64
 9   X10     171 non-null    float64
 10  X11     171 non-null    float64
 11  X12     171 non-null    float64
 12  X13     171 non-null    float64
 13  X14     171 non-null    float64
 14  X15     171 non-null    float64
 15  X16     171 non-null    float64
 16  X17     171 non-null    float64
 17  X18     171 non-null    float64
 18  X19     171 non-null    float64
 19  X20     171 non-null    float64
 20  X21     171 non-null    float64
 21  X22     171 non-null    float64
 22  X2

In [ ]:
print(df.shape)

(171, 24)


In [ ]:
print(df["Y"].value_counts())
print(df["Y"].value_counts(normalize=True).round(2))

Y
2    125
1     46
Name: count, dtype: int64
Y
2    0.73
1    0.27
Name: proportion, dtype: float64


In [ ]:
df.info()
df.describe()
df.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171 entries, 0 to 170
Data columns (total 24 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X1      171 non-null    float64
 1   X2      171 non-null    float64
 2   X3      171 non-null    float64
 3   X4      171 non-null    float64
 4   X5      171 non-null    float64
 5   X6      171 non-null    float64
 6   X7      171 non-null    float64
 7   X8      171 non-null    float64
 8   X9      171 non-null    float64
 9   X10     171 non-null    float64
 10  X11     171 non-null    float64
 11  X12     171 non-null    float64
 12  X13     171 non-null    float64
 13  X14     171 non-null    float64
 14  X15     171 non-null    float64
 15  X16     171 non-null    float64
 16  X17     171 non-null    float64
 17  X18     171 non-null    float64
 18  X19     171 non-null    float64
 19  X20     171 non-null    float64
 20  X21     171 non-null    float64
 21  X22     171 non-null    float64
 22  X2

,0
X1,171
X2,170
X3,171
X4,171
X5,171
X6,171
X7,171
X8,171
X9,171
X10,171


**Define X and Y**

In [ ]:
X = df.drop('Y', axis=1).values

#Conversion of labels

y = df['Y'].replace({1:0,2:1}).values

print("Unique y values:",np.unique(y))

Unique y values: [0 1]


**10-fold Stratified CV**

In [ ]:
from sklearn.model_selection import StratifiedKFold


In [ ]:
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

# **Pipeline**

In [ ]:
from tensorflow.keras import backend as K
import gc

In [ ]:
def evaluate_keras_model(model_name, build_fn, X_data, y_data, sequence_model=False,
                         feature_selection=None, k_features=None,
                         epochs=20, batch_size=16):

    acc_list = []
    prec_list = []
    recall_list = []
    f1_list = []
    auc_list = []
    spec_list = []



    start_time = time.time()

    for fold_i, (train_rows, test_rows) in enumerate(skf.split(X_data, y_data), start=1):

        # 1) Split
        X_train, X_test = X_data[train_rows], X_data[test_rows]
        y_train, y_test = y_data[train_rows], y_data[test_rows]

        # 2) Feature selection

        if feature_selection == "mi":
            selector = SelectKBest(score_func=mutual_info_classif, k=k_features)
            X_train = selector.fit_transform(X_train, y_train)
            X_test = selector.transform(X_test)

        elif feature_selection == "sfs":
            selector = SequentialFeatureSelector(
                LogisticRegression(max_iter=1000),
                n_features_to_select=k_features,
                direction="forward",
                scoring="accuracy",
                cv=5
            )
            X_train = selector.fit_transform(X_train, y_train)
            X_test = selector.transform(X_test)

        # 2) Scale
        scaler = StandardScaler()
        X_train = scaler.fit_transform(X_train)
        X_test = scaler.transform(X_test)

        # 3) Reshape only for sequence models

        if sequence_model:
            X_train = X_train.reshape((X_train.shape[0], 1, X_train.shape[1]))
            X_test = X_test.reshape((X_test.shape[0], 1, X_test.shape[1]))
            n_features = X_train.shape[2]
        else:
            n_features = X_train.shape[1]

        # 4) Build fresh model for this fold
        model = build_fn(n_features)

        # 5) Train
        model.fit(
            X_train, y_train,
            epochs=epochs,
            batch_size=batch_size,
            verbose=0
        )

        # 6) Predict
        y_prob = model.predict(X_test, verbose=0).ravel()
        y_pred = (y_prob >= 0.7).astype(int)

        # 7) Metrics
        acc_list.append(accuracy_score(y_test, y_pred))
        prec_list.append(precision_score(y_test, y_pred, zero_division=0))
        recall_list.append(recall_score(y_test, y_pred, zero_division=0))
        f1_list.append(f1_score(y_test, y_pred, zero_division=0))
        auc_list.append(roc_auc_score(y_test, y_prob))

        cm = confusion_matrix(y_test, y_pred, labels=[0, 1])
        tn, fp, fn, tp = cm.ravel()

        print("Actual 0s:", np.sum(y_test == 0), "Actual 1s:", np.sum(y_test == 1))
        print("Pred  0s:", np.sum(y_pred == 0), "Pred  1s:", np.sum(y_pred == 1))
        print("Confusion matrix:")
        print(cm)
        print("TN =", tn, "FP =", fp, "FN =", fn, "TP =", tp)
        print("-" * 40)

        specificity = tn / (tn + fp) if (tn + fp) > 0 else 0
        spec_list.append(specificity)


        #Delete model - My session keeps crashing because I'm using all RAM

        del model, X_train, X_test, y_train, y_test, y_prob, y_pred, cm
        K.clear_session()
        gc.collect()

    runtime = time.time() - start_time


    print(f"\n{model_name} SUMMARY:")
    print(f"     Runtime: {runtime:.2f}s")
    print(f"     accuracy   : {np.mean(acc_list):.4f}")
    print(f"     precision  : {np.mean(prec_list):.4f}")
    print(f"     recall     : {np.mean(recall_list):.4f}")
    print(f"     sensitivity: {np.mean(recall_list):.4f}")
    print(f"     specificity: {np.mean(spec_list):.4f}")
    print(f"     f1         : {np.mean(f1_list):.4f}")
    print(f"     roc_auc    : {np.mean(auc_list):.4f}")

    return {
        "Model": model_name,
        "Accuracy": np.mean(acc_list),
        "Sensitivity": np.mean(recall_list),
        "Specificity": np.mean(spec_list),
        "AUC": np.mean(auc_list),
        "F1": np.mean(f1_list)
    }

results = []


In [ ]:

print(np.bincount(y))

[ 46 125]


# **Evaluation**

In [ ]:
!pip install keras

In [ ]:
import time
from sklearn.feature_selection import SelectKBest, mutual_info_classif, SequentialFeatureSelector
from keras.models import Sequential
from keras.layers import SimpleRNN, LSTM, Bidirectional, GRU, Dense
from tensorflow.keras.utils import plot_model
from tensorflow.keras.layers import Dense, Dropout, Input
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
import tensorflow as tf

## RNN

In [ ]:
#Model

def build_rnn(n_features):
    model = Sequential([
       SimpleRNN(units=16, return_sequences=True, input_shape=(1, n_features)),
       SimpleRNN(units=8),
       Dense(1, activation="sigmoid")
    ])
    model.compile(
        optimizer="adam",
        loss="binary_crossentropy",
        metrics=["accuracy"]
    )
    return model

#Evaluate

results.append(evaluate_keras_model(
    "RNN_SetA",
    build_rnn,
    X_data=X,
    y_data=y,
    feature_selection=None,
    sequence_model=True
))
results.append(evaluate_keras_model(
    "RNN_SetB",
    build_rnn,
    X_data=X,
    y_data=y,
    feature_selection="mi",
    k_features=10,
    sequence_model=True
))
results.append(evaluate_keras_model(
    "RNN_SetC",
    build_rnn,
    X_data=X,
    y_data=y,
    feature_selection="sfs",
    k_features=10,
    sequence_model=True
))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 13
Pred  0s: 9 Pred  1s: 9
Confusion matrix:
[[3 2]
 [6 7]]
TN = 3 FP = 2 FN = 6 TP = 7
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 7 Pred  1s: 10
Confusion matrix:
[[2 2]
 [5 8]]
TN = 2 FP = 2 FN = 5 TP = 8
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 10 Pred  1s: 7
Confusion matrix:
[[3 1]
 [7 6]]
TN = 3 FP = 1 FN = 7 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 9 Pred  1s: 8
Confusion matrix:
[[3 1]
 [6 7]]
TN = 3 FP = 1 FN = 6 TP = 7
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 13 Pred  1s: 4
Confusion matrix:
[[4 0]
 [9 4]]
TN = 4 FP = 0 FN = 9 TP = 4
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 5 Pred  1s: 12
Confusion matrix:
[[1 4]
 [4 8]]
TN = 1 FP = 4 FN = 4 TP = 8
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 9 Pred  1s: 8
Confusion matrix:
[[3 2]
 [6 6]]
TN = 3 FP = 2 FN = 6 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 8 Pred  1s: 9
Confusion matrix:
[[4 1]
 [4 8]]
TN = 4 FP = 1 FN = 4 TP = 8
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 8 Pred  1s: 9
Confusion matrix:
[[2 3]
 [6 6]]
TN = 2 FP = 3 FN = 6 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 12 Pred  1s: 5
Confusion matrix:
[[4 1]
 [8 4]]
TN = 4 FP = 1 FN = 8 TP = 4
----------------------------------------

RNN_SetA SUMMARY:
     Runtime: 78.52s
     accuracy   : 0.5438
     precision  : 0.8082
     recall     : 0.5128
     sensitivity: 0.5128
     specificity: 0.6400
     f1         : 0.6140
     roc_auc    : 0.6169


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 13
Pred  0s: 12 Pred  1s: 6
Confusion matrix:
[[5 0]
 [7 6]]
TN = 5 FP = 0 FN = 7 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 6 Pred  1s: 11
Confusion matrix:
[[2 2]
 [4 9]]
TN = 2 FP = 2 FN = 4 TP = 9
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 8 Pred  1s: 9
Confusion matrix:
[[2 2]
 [6 7]]
TN = 2 FP = 2 FN = 6 TP = 7
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 10 Pred  1s: 7
Confusion matrix:
[[3 1]
 [7 6]]
TN = 3 FP = 1 FN = 7 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 10 Pred  1s: 7
Confusion matrix:
[[3 1]
 [7 6]]
TN = 3 FP = 1 FN = 7 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 7 Pred  1s: 10
Confusion matrix:
[[1 4]
 [6 6]]
TN = 1 FP = 4 FN = 6 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 6 Pred  1s: 11
Confusion matrix:
[[1 4]
 [5 7]]
TN = 1 FP = 4 FN = 5 TP = 7
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 6 Pred  1s: 11
Confusion matrix:
[[2 3]
 [4 8]]
TN = 2 FP = 3 FN = 4 TP = 8
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 9 Pred  1s: 8
Confusion matrix:
[[2 3]
 [7 5]]
TN = 2 FP = 3 FN = 7 TP = 5
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 13 Pred  1s: 4
Confusion matrix:
[[5 0]
 [8 4]]
TN = 5 FP = 0 FN = 8 TP = 4
----------------------------------------

RNN_SetB SUMMARY:
     Runtime: 66.09s
     accuracy   : 0.5258
     precision  : 0.7899
     recall     : 0.5115
     sensitivity: 0.5115
     specificity: 0.5700
     f1         : 0.6068
     roc_auc    : 0.5350


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 13
Pred  0s: 9 Pred  1s: 9
Confusion matrix:
[[3 2]
 [6 7]]
TN = 3 FP = 2 FN = 6 TP = 7
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 10 Pred  1s: 7
Confusion matrix:
[[3 1]
 [7 6]]
TN = 3 FP = 1 FN = 7 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 8 Pred  1s: 9
Confusion matrix:
[[2 2]
 [6 7]]
TN = 2 FP = 2 FN = 6 TP = 7
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 7 Pred  1s: 10
Confusion matrix:
[[3 1]
 [4 9]]
TN = 3 FP = 1 FN = 4 TP = 9
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 12 Pred  1s: 5
Confusion matrix:
[[4 0]
 [8 5]]
TN = 4 FP = 0 FN = 8 TP = 5
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 7 Pred  1s: 10
Confusion matrix:
[[2 3]
 [5 7]]
TN = 2 FP = 3 FN = 5 TP = 7
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 11 Pred  1s: 6
Confusion matrix:
[[3 2]
 [8 4]]
TN = 3 FP = 2 FN = 8 TP = 4
----------------------------------------


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

Actual 0s: 5 Actual 1s: 12
Pred  0s: 8 Pred  1s: 9
Confusion matrix:
[[3 2]
 [5 7]]
TN = 3 FP = 2 FN = 5 TP = 7
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 8 Pred  1s: 9
Confusion matrix:
[[2 3]
 [6 6]]
TN = 2 FP = 3 FN = 6 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 13 Pred  1s: 4
Confusion matrix:
[[4 1]
 [9 3]]
TN = 4 FP = 1 FN = 9 TP = 3
----------------------------------------

RNN_SetC SUMMARY:
     Runtime: 213.34s
     accuracy   : 0.5261
     precision  : 0.7874
     recall     : 0.4865
     sensitivity: 0.4865
     specificity: 0.6400
     f1         : 0.5905
     roc_auc    : 0.5377


##DNN

In [ ]:
#Model

def build_dnn(n_features):
    model = Sequential([
        Input(shape=(n_features,)),
        Dense(128, activation='relu'),
        Dropout(0.3),
        Dense(64, activation="relu"),
        Dropout(0.3),
        Dense(32, activation="relu"),
        Dense(1, activation="sigmoid")
    ])
    model.compile(
        optimizer="adam",
        loss="binary_crossentropy",
        metrics=["accuracy"]
    )
    return model

#Evaluate

results.append(evaluate_keras_model(
    "DNN_SetA",
    build_dnn,
    X_data=X,
    y_data=y,
    feature_selection=None
))
results.append(evaluate_keras_model(
    "DNN_SetB",
    build_dnn,
    X_data=X,
    y_data=y,
    feature_selection="mi",
    k_features=10
))
results.append(evaluate_keras_model(
    "DNN_SetC",
    build_dnn,
    X_data=X,
    y_data=y,
    feature_selection="sfs",
    k_features=10
))

Actual 0s: 5 Actual 1s: 13
Pred  0s: 10 Pred  1s: 8
Confusion matrix:
[[5 0]
 [5 8]]
TN = 5 FP = 0 FN = 5 TP = 8
----------------------------------------
Actual 0s: 4 Actual 1s: 13
Pred  0s: 6 Pred  1s: 11
Confusion matrix:
[[2 2]
 [4 9]]
TN = 2 FP = 2 FN = 4 TP = 9
----------------------------------------
Actual 0s: 4 Actual 1s: 13
Pred  0s: 5 Pred  1s: 12
Confusion matrix:
[[1 3]
 [4 9]]
TN = 1 FP = 3 FN = 4 TP = 9
----------------------------------------
Actual 0s: 4 Actual 1s: 13
Pred  0s: 5 Pred  1s: 12
Confusion matrix:
[[1 3]
 [4 9]]
TN = 1 FP = 3 FN = 4 TP = 9
----------------------------------------
Actual 0s: 4 Actual 1s: 13
Pred  0s: 9 Pred  1s: 8
Confusion matrix:
[[1 3]
 [8 5]]
TN = 1 FP = 3 FN = 8 TP = 5
----------------------------------------
Actual 0s: 5 Actual 1s: 12
Pred  0s: 7 Pred  1s: 10
Confusion matrix:
[[2 3]
 [5 7]]
TN = 2 FP = 3 FN = 5 TP = 7
----------------------------------------
Actual 0s: 5 Actual 1s: 12
Pred  0s: 9 Pred  1s: 8
Confusion matrix:
[[4 1]
 

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

Actual 0s: 5 Actual 1s: 12
Pred  0s: 7 Pred  1s: 10
Confusion matrix:
[[4 1]
 [3 9]]
TN = 4 FP = 1 FN = 3 TP = 9
----------------------------------------
Actual 0s: 5 Actual 1s: 12
Pred  0s: 9 Pred  1s: 8
Confusion matrix:
[[3 2]
 [6 6]]
TN = 3 FP = 2 FN = 6 TP = 6
----------------------------------------
Actual 0s: 5 Actual 1s: 12
Pred  0s: 14 Pred  1s: 3
Confusion matrix:
[[5 0]
 [9 3]]
TN = 5 FP = 0 FN = 9 TP = 3
----------------------------------------

DNN_SetC SUMMARY:
     Runtime: 199.89s
     accuracy   : 0.6193
     precision  : 0.8317
     recall     : 0.6122
     sensitivity: 0.6122
     specificity: 0.6200
     f1         : 0.6884
     roc_auc    : 0.5772


##LSTM

###LSTM

In [ ]:
#Model

def build_LSTM(n_features):
    model = Sequential()
    model.add(LSTM(16, return_sequences=False, input_shape=(1, n_features)))
    model.add(Dense(1, activation="sigmoid"))
    model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
    return model

#Evaluate

results.append(evaluate_keras_model(
    "LSTM_SetA",
    build_LSTM,
    X_data=X,
    y_data=y,
    feature_selection=None,
    sequence_model=True
))
results.append(evaluate_keras_model(
    "LSTM_SetB",
    build_LSTM,
    X_data=X,
    y_data=y,
    feature_selection="mi",
    k_features=10,
    sequence_model=True
))
results.append(evaluate_keras_model(
    "LSTM_SetC",
    build_LSTM,
    X_data=X,
    y_data=y,
    feature_selection="sfs",
    k_features=10,
    sequence_model=True
))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 13
Pred  0s: 11 Pred  1s: 7
Confusion matrix:
[[4 1]
 [7 6]]
TN = 4 FP = 1 FN = 7 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 7 Pred  1s: 10
Confusion matrix:
[[2 2]
 [5 8]]
TN = 2 FP = 2 FN = 5 TP = 8
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 9 Pred  1s: 8
Confusion matrix:
[[3 1]
 [6 7]]
TN = 3 FP = 1 FN = 6 TP = 7
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 9 Pred  1s: 8
Confusion matrix:
[[3 1]
 [6 7]]
TN = 3 FP = 1 FN = 6 TP = 7
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 10 Pred  1s: 7
Confusion matrix:
[[2 2]
 [8 5]]
TN = 2 FP = 2 FN = 8 TP = 5
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 9 Pred  1s: 8
Confusion matrix:
[[2 3]
 [7 5]]
TN = 2 FP = 3 FN = 7 TP = 5
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 13 Pred  1s: 4
Confusion matrix:
[[ 3  2]
 [10  2]]
TN = 3 FP = 2 FN = 10 TP = 2
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 8 Pred  1s: 9
Confusion matrix:
[[3 2]
 [5 7]]
TN = 3 FP = 2 FN = 5 TP = 7
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 7 Pred  1s: 10
Confusion matrix:
[[1 4]
 [6 6]]
TN = 1 FP = 4 FN = 6 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 9 Pred  1s: 8
Confusion matrix:
[[3 2]
 [6 6]]
TN = 3 FP = 2 FN = 6 TP = 6
----------------------------------------

LSTM_SetA SUMMARY:
     Runtime: 60.44s
     accuracy   : 0.4967
     precision  : 0.7374
     recall     : 0.4705
     sensitivity: 0.4705
     specificity: 0.5700
     f1         : 0.5691
     roc_auc    : 0.5812


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 13
Pred  0s: 15 Pred  1s: 3
Confusion matrix:
[[ 5  0]
 [10  3]]
TN = 5 FP = 0 FN = 10 TP = 3
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 11 Pred  1s: 6
Confusion matrix:
[[2 2]
 [9 4]]
TN = 2 FP = 2 FN = 9 TP = 4
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 15 Pred  1s: 2
Confusion matrix:
[[ 4  0]
 [11  2]]
TN = 4 FP = 0 FN = 11 TP = 2
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 14 Pred  1s: 3
Confusion matrix:
[[ 4  0]
 [10  3]]
TN = 4 FP = 0 FN = 10 TP = 3
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 14 Pred  1s: 3
Confusion matrix:
[[ 4  0]
 [10  3]]
TN = 4 FP = 0 FN = 10 TP = 3
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 9 Pred  1s: 8
Confusion matrix:
[[2 3]
 [7 5]]
TN = 2 FP = 3 FN = 7 TP = 5
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 14 Pred  1s: 3
Confusion matrix:
[[ 3  2]
 [11  1]]
TN = 3 FP = 2 FN = 11 TP = 1
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 13 Pred  1s: 4
Confusion matrix:
[[4 1]
 [9 3]]
TN = 4 FP = 1 FN = 9 TP = 3
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 13 Pred  1s: 4
Confusion matrix:
[[4 1]
 [9 3]]
TN = 4 FP = 1 FN = 9 TP = 3
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 15 Pred  1s: 2
Confusion matrix:
[[ 5  0]
 [10  2]]
TN = 5 FP = 0 FN = 10 TP = 2
----------------------------------------

LSTM_SetB SUMMARY:
     Runtime: 64.40s
     accuracy   : 0.3856
     precision  : 0.8125
     recall     : 0.2321
     sensitivity: 0.2321
     specificity: 0.8100
     f1         : 0.3482
     roc_auc    : 0.5617


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 13
Pred  0s: 15 Pred  1s: 3
Confusion matrix:
[[ 5  0]
 [10  3]]
TN = 5 FP = 0 FN = 10 TP = 3
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 13 Pred  1s: 4
Confusion matrix:
[[4 0]
 [9 4]]
TN = 4 FP = 0 FN = 9 TP = 4
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 13 Pred  1s: 4
Confusion matrix:
[[ 3  1]
 [10  3]]
TN = 3 FP = 1 FN = 10 TP = 3
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 9 Pred  1s: 8
Confusion matrix:
[[4 0]
 [5 8]]
TN = 4 FP = 0 FN = 5 TP = 8
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 12 Pred  1s: 5
Confusion matrix:
[[ 2  2]
 [10  3]]
TN = 2 FP = 2 FN = 10 TP = 3
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 9 Pred  1s: 8
Confusion matrix:
[[2 3]
 [7 5]]
TN = 2 FP = 3 FN = 7 TP = 5
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 14 Pred  1s: 3
Confusion matrix:
[[ 3  2]
 [11  1]]
TN = 3 FP = 2 FN = 11 TP = 1
----------------------------------------


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

Actual 0s: 5 Actual 1s: 12
Pred  0s: 11 Pred  1s: 6
Confusion matrix:
[[4 1]
 [7 5]]
TN = 4 FP = 1 FN = 7 TP = 5
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 10 Pred  1s: 7
Confusion matrix:
[[3 2]
 [7 5]]
TN = 3 FP = 2 FN = 7 TP = 5
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 14 Pred  1s: 3
Confusion matrix:
[[ 4  1]
 [10  2]]
TN = 4 FP = 1 FN = 10 TP = 2
----------------------------------------

LSTM_SetC SUMMARY:
     Runtime: 213.49s
     accuracy   : 0.4268
     precision  : 0.7523
     recall     : 0.3115
     sensitivity: 0.3115
     specificity: 0.7450
     f1         : 0.4276
     roc_auc    : 0.5449


###Stacked LSTM

In [ ]:
#Model

def build_STACKEDlstm(n_features):
    model = Sequential()
    model.add(LSTM(16, return_sequences=True, input_shape=(1, n_features)))
    model.add(LSTM(8, return_sequences=False))
    model.add(Dense(1, activation="sigmoid"))
    model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
    return model

#Evaluate

results.append(evaluate_keras_model(
    "StackedLSTM_SetA",
    build_STACKEDlstm,
    X_data=X,
    y_data=y,
    feature_selection=None,
    sequence_model=True,
))
results.append(evaluate_keras_model(
    "StackedLSTM_SetB",
    build_STACKEDlstm,
    X_data=X,
    y_data=y,
    feature_selection="mi",
    k_features=10,
    sequence_model=True
))
results.append(evaluate_keras_model(
    "StackedLSTM_SetC",
    build_STACKEDlstm,
    X_data=X,
    y_data=y,
    feature_selection="sfs",
    k_features=10,
    sequence_model=True
))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 13
Pred  0s: 7 Pred  1s: 11
Confusion matrix:
[[3 2]
 [4 9]]
TN = 3 FP = 2 FN = 4 TP = 9
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 5 Pred  1s: 12
Confusion matrix:
[[ 3  1]
 [ 2 11]]
TN = 3 FP = 1 FN = 2 TP = 11
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 5 Pred  1s: 12
Confusion matrix:
[[ 2  2]
 [ 3 10]]
TN = 2 FP = 2 FN = 3 TP = 10
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 9 Pred  1s: 8
Confusion matrix:
[[3 1]
 [6 7]]
TN = 3 FP = 1 FN = 6 TP = 7
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 7 Pred  1s: 10
Confusion matrix:
[[1 3]
 [6 7]]
TN = 1 FP = 3 FN = 6 TP = 7
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 7 Pred  1s: 10
Confusion matrix:
[[2 3]
 [5 7]]
TN = 2 FP = 3 FN = 5 TP = 7
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 12 Pred  1s: 5
Confusion matrix:
[[3 2]
 [9 3]]
TN = 3 FP = 2 FN = 9 TP = 3
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 7 Pred  1s: 10
Confusion matrix:
[[4 1]
 [3 9]]
TN = 4 FP = 1 FN = 3 TP = 9
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 6 Pred  1s: 11
Confusion matrix:
[[0 5]
 [6 6]]
TN = 0 FP = 5 FN = 6 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 6 Pred  1s: 11
Confusion matrix:
[[3 2]
 [3 9]]
TN = 3 FP = 2 FN = 3 TP = 9
----------------------------------------

StackedLSTM_SetA SUMMARY:
     Runtime: 86.93s
     accuracy   : 0.5961
     precision  : 0.7707
     recall     : 0.6218
     sensitivity: 0.6218
     specificity: 0.5250
     f1         : 0.6817
     roc_auc    : 0.6078


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 13
Pred  0s: 10 Pred  1s: 8
Confusion matrix:
[[4 1]
 [6 7]]
TN = 4 FP = 1 FN = 6 TP = 7
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 7 Pred  1s: 10
Confusion matrix:
[[2 2]
 [5 8]]
TN = 2 FP = 2 FN = 5 TP = 8
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 8 Pred  1s: 9
Confusion matrix:
[[3 1]
 [5 8]]
TN = 3 FP = 1 FN = 5 TP = 8
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 8 Pred  1s: 9
Confusion matrix:
[[3 1]
 [5 8]]
TN = 3 FP = 1 FN = 5 TP = 8
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 11 Pred  1s: 6
Confusion matrix:
[[3 1]
 [8 5]]
TN = 3 FP = 1 FN = 8 TP = 5
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 8 Pred  1s: 9
Confusion matrix:
[[2 3]
 [6 6]]
TN = 2 FP = 3 FN = 6 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 13 Pred  1s: 4
Confusion matrix:
[[ 3  2]
 [10  2]]
TN = 3 FP = 2 FN = 10 TP = 2
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 9 Pred  1s: 8
Confusion matrix:
[[3 2]
 [6 6]]
TN = 3 FP = 2 FN = 6 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 8 Pred  1s: 9
Confusion matrix:
[[2 3]
 [6 6]]
TN = 2 FP = 3 FN = 6 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 8 Pred  1s: 9
Confusion matrix:
[[4 1]
 [4 8]]
TN = 4 FP = 1 FN = 4 TP = 8
----------------------------------------

StackedLSTM_SetB SUMMARY:
     Runtime: 89.95s
     accuracy   : 0.5435
     precision  : 0.7758
     recall     : 0.5103
     sensitivity: 0.5103
     specificity: 0.6350
     f1         : 0.6098
     roc_auc    : 0.5695


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 13
Pred  0s: 12 Pred  1s: 6
Confusion matrix:
[[5 0]
 [7 6]]
TN = 5 FP = 0 FN = 7 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 9 Pred  1s: 8
Confusion matrix:
[[2 2]
 [7 6]]
TN = 2 FP = 2 FN = 7 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 13 Pred  1s: 4
Confusion matrix:
[[ 3  1]
 [10  3]]
TN = 3 FP = 1 FN = 10 TP = 3
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 9 Pred  1s: 8
Confusion matrix:
[[3 1]
 [6 7]]
TN = 3 FP = 1 FN = 6 TP = 7
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 8 Pred  1s: 9
Confusion matrix:
[[2 2]
 [6 7]]
TN = 2 FP = 2 FN = 6 TP = 7
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 8 Pred  1s: 9
Confusion matrix:
[[2 3]
 [6 6]]
TN = 2 FP = 3 FN = 6 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 11 Pred  1s: 6
Confusion matrix:
[[3 2]
 [8 4]]
TN = 3 FP = 2 FN = 8 TP = 4
----------------------------------------


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

Actual 0s: 5 Actual 1s: 12
Pred  0s: 10 Pred  1s: 7
Confusion matrix:
[[4 1]
 [6 6]]
TN = 4 FP = 1 FN = 6 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 9 Pred  1s: 8
Confusion matrix:
[[2 3]
 [7 5]]
TN = 2 FP = 3 FN = 7 TP = 5
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 11 Pred  1s: 6
Confusion matrix:
[[2 3]
 [9 3]]
TN = 2 FP = 3 FN = 9 TP = 3
----------------------------------------

StackedLSTM_SetC SUMMARY:
     Runtime: 236.76s
     accuracy   : 0.4729
     precision  : 0.7468
     recall     : 0.4231
     sensitivity: 0.4231
     specificity: 0.6100
     f1         : 0.5340
     roc_auc    : 0.5412


###BiLSTM

In [ ]:
#Model

def build_biLSTM(n_features):
    model = Sequential()
    model.add(Bidirectional(LSTM(units=16, return_sequences=True), input_shape=(1,n_features )))
    model.add(Bidirectional(LSTM(units=8)))
    model.add(Dense(1, activation="sigmoid"))
    model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
    return model

#Evaluate

results.append(evaluate_keras_model(
   "biLSTM_SetA",
    build_biLSTM,
    X_data=X,
    y_data=y,
    feature_selection=None,
    sequence_model=True,
))
results.append(evaluate_keras_model(
    "biLSTM_SetB",
    build_biLSTM,
    X_data=X,
    y_data=y,
    feature_selection="mi",
    k_features=10,
    sequence_model=True
))
results.append(evaluate_keras_model(
    "biLSTM_SetC",
    build_biLSTM,
    X_data=X,
    y_data=y,
    feature_selection="sfs",
    k_features=10,
    sequence_model=True
))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 13
Pred  0s: 8 Pred  1s: 10
Confusion matrix:
[[4 1]
 [4 9]]
TN = 4 FP = 1 FN = 4 TP = 9
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 4 Pred  1s: 13
Confusion matrix:
[[ 1  3]
 [ 3 10]]
TN = 1 FP = 3 FN = 3 TP = 10
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 6 Pred  1s: 11
Confusion matrix:
[[ 3  1]
 [ 3 10]]
TN = 3 FP = 1 FN = 3 TP = 10
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 8 Pred  1s: 9
Confusion matrix:
[[3 1]
 [5 8]]
TN = 3 FP = 1 FN = 5 TP = 8
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 8 Pred  1s: 9
Confusion matrix:
[[1 3]
 [7 6]]
TN = 1 FP = 3 FN = 7 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 6 Pred  1s: 11
Confusion matrix:
[[2 3]
 [4 8]]
TN = 2 FP = 3 FN = 4 TP = 8
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 11 Pred  1s: 6
Confusion matrix:
[[3 2]
 [8 4]]
TN = 3 FP = 2 FN = 8 TP = 4
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 7 Pred  1s: 10
Confusion matrix:
[[3 2]
 [4 8]]
TN = 3 FP = 2 FN = 4 TP = 8
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 6 Pred  1s: 11
Confusion matrix:
[[1 4]
 [5 7]]
TN = 1 FP = 4 FN = 5 TP = 7
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 7 Pred  1s: 10
Confusion matrix:
[[3 2]
 [4 8]]
TN = 3 FP = 2 FN = 4 TP = 8
----------------------------------------

biLSTM_SetA SUMMARY:
     Runtime: 134.41s
     accuracy   : 0.5958
     precision  : 0.7764
     recall     : 0.6224
     sensitivity: 0.6224
     specificity: 0.5200
     f1         : 0.6861
     roc_auc    : 0.6160


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 13
Pred  0s: 9 Pred  1s: 9
Confusion matrix:
[[4 1]
 [5 8]]
TN = 4 FP = 1 FN = 5 TP = 8
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 3 Pred  1s: 14
Confusion matrix:
[[ 2  2]
 [ 1 12]]
TN = 2 FP = 2 FN = 1 TP = 12
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 5 Pred  1s: 12
Confusion matrix:
[[ 2  2]
 [ 3 10]]
TN = 2 FP = 2 FN = 3 TP = 10
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 7 Pred  1s: 10
Confusion matrix:
[[3 1]
 [4 9]]
TN = 3 FP = 1 FN = 4 TP = 9
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 8 Pred  1s: 9
Confusion matrix:
[[1 3]
 [7 6]]
TN = 1 FP = 3 FN = 7 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 8 Pred  1s: 9
Confusion matrix:
[[2 3]
 [6 6]]
TN = 2 FP = 3 FN = 6 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 13 Pred  1s: 4
Confusion matrix:
[[ 3  2]
 [10  2]]
TN = 3 FP = 2 FN = 10 TP = 2
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 7 Pred  1s: 10
Confusion matrix:
[[2 3]
 [5 7]]
TN = 2 FP = 3 FN = 5 TP = 7
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 8 Pred  1s: 9
Confusion matrix:
[[2 3]
 [6 6]]
TN = 2 FP = 3 FN = 6 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 6 Pred  1s: 11
Confusion matrix:
[[3 2]
 [3 9]]
TN = 3 FP = 2 FN = 3 TP = 9
----------------------------------------

biLSTM_SetB SUMMARY:
     Runtime: 145.57s
     accuracy   : 0.5784
     precision  : 0.7498
     recall     : 0.5962
     sensitivity: 0.5962
     specificity: 0.5200
     f1         : 0.6556
     roc_auc    : 0.5768


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 13
Pred  0s: 10 Pred  1s: 8
Confusion matrix:
[[5 0]
 [5 8]]
TN = 5 FP = 0 FN = 5 TP = 8
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 6 Pred  1s: 11
Confusion matrix:
[[2 2]
 [4 9]]
TN = 2 FP = 2 FN = 4 TP = 9
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 7 Pred  1s: 10
Confusion matrix:
[[2 2]
 [5 8]]
TN = 2 FP = 2 FN = 5 TP = 8
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 6 Pred  1s: 11
Confusion matrix:
[[ 3  1]
 [ 3 10]]
TN = 3 FP = 1 FN = 3 TP = 10
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 4 Actual 1s: 13
Pred  0s: 7 Pred  1s: 10
Confusion matrix:
[[2 2]
 [5 8]]
TN = 2 FP = 2 FN = 5 TP = 8
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 7 Pred  1s: 10
Confusion matrix:
[[2 3]
 [5 7]]
TN = 2 FP = 3 FN = 5 TP = 7
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 11 Pred  1s: 6
Confusion matrix:
[[3 2]
 [8 4]]
TN = 3 FP = 2 FN = 8 TP = 4
----------------------------------------


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

Actual 0s: 5 Actual 1s: 12
Pred  0s: 10 Pred  1s: 7
Confusion matrix:
[[4 1]
 [6 6]]
TN = 4 FP = 1 FN = 6 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 7 Pred  1s: 10
Confusion matrix:
[[1 4]
 [6 6]]
TN = 1 FP = 4 FN = 6 TP = 6
----------------------------------------


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Actual 0s: 5 Actual 1s: 12
Pred  0s: 10 Pred  1s: 7
Confusion matrix:
[[3 2]
 [7 5]]
TN = 3 FP = 2 FN = 7 TP = 5
----------------------------------------

biLSTM_SetC SUMMARY:
     Runtime: 297.74s
     accuracy   : 0.5722
     precision  : 0.7865
     recall     : 0.5641
     sensitivity: 0.5641
     specificity: 0.5850
     f1         : 0.6521
     roc_auc    : 0.6031


## CNN

In [ ]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Reshape, Conv1D, MaxPooling1D, Flatten
from tensorflow.keras.layers import Dense, Dropout, Input
from tensorflow.keras.optimizers import Adam

In [ ]:
#Model

def build_cnn(n_features):
    model = Sequential([
        Input(shape=(n_features,)),
        Reshape((n_features,1)),
        Conv1D(filters=32, kernel_size=3, activation="relu", padding="same"),
        MaxPooling1D(pool_size=2),
        Flatten(),
        Dense(32, activation="relu"),
        Dropout(0.3),
        Dense(1, activation="sigmoid")
    ])
    model.compile(
        optimizer="adam",
        loss="binary_crossentropy",
        metrics=["accuracy"]
    )
    return model

#Evaluate

results.append(evaluate_keras_model(
    "CNN_SetA",
    build_cnn,
    X_data=X,
    y_data=y,
    feature_selection=None,
))
results.append(evaluate_keras_model(
    "CNN_SetB",
    build_cnn,
    X_data=X,
    y_data=y,
    feature_selection="mi",
    k_features=10,
))
results.append(evaluate_keras_model(
    "CNN_SetC",
    build_cnn,
    X_data=X,
    y_data=y,
    feature_selection="sfs",
    k_features=10,
))

Actual 0s: 5 Actual 1s: 13
Pred  0s: 8 Pred  1s: 10
Confusion matrix:
[[4 1]
 [4 9]]
TN = 4 FP = 1 FN = 4 TP = 9
----------------------------------------
Actual 0s: 4 Actual 1s: 13
Pred  0s: 3 Pred  1s: 14
Confusion matrix:
[[ 1  3]
 [ 2 11]]
TN = 1 FP = 3 FN = 2 TP = 11
----------------------------------------
Actual 0s: 4 Actual 1s: 13
Pred  0s: 6 Pred  1s: 11
Confusion matrix:
[[2 2]
 [4 9]]
TN = 2 FP = 2 FN = 4 TP = 9
----------------------------------------
Actual 0s: 4 Actual 1s: 13
Pred  0s: 6 Pred  1s: 11
Confusion matrix:
[[1 3]
 [5 8]]
TN = 1 FP = 3 FN = 5 TP = 8
----------------------------------------
Actual 0s: 4 Actual 1s: 13
Pred  0s: 4 Pred  1s: 13
Confusion matrix:
[[ 1  3]
 [ 3 10]]
TN = 1 FP = 3 FN = 3 TP = 10
----------------------------------------
Actual 0s: 5 Actual 1s: 12
Pred  0s: 6 Pred  1s: 11
Confusion matrix:
[[2 3]
 [4 8]]
TN = 2 FP = 3 FN = 4 TP = 8
----------------------------------------
Actual 0s: 5 Actual 1s: 12
Pred  0s: 10 Pred  1s: 7
Confusion matr

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

Actual 0s: 5 Actual 1s: 12
Pred  0s: 9 Pred  1s: 8
Confusion matrix:
[[3 2]
 [6 6]]
TN = 3 FP = 2 FN = 6 TP = 6
----------------------------------------
Actual 0s: 5 Actual 1s: 12
Pred  0s: 8 Pred  1s: 9
Confusion matrix:
[[2 3]
 [6 6]]
TN = 2 FP = 3 FN = 6 TP = 6
----------------------------------------
Actual 0s: 5 Actual 1s: 12
Pred  0s: 9 Pred  1s: 8
Confusion matrix:
[[2 3]
 [7 5]]
TN = 2 FP = 3 FN = 7 TP = 5
----------------------------------------

CNN_SetC SUMMARY:
     Runtime: 234.82s
     accuracy   : 0.5601
     precision  : 0.7572
     recall     : 0.5808
     sensitivity: 0.5808
     specificity: 0.4950
     f1         : 0.6540
     roc_auc    : 0.5558


## Model Comparison

In [ ]:
results_df = pd.DataFrame(results)

#Results

results_df = results_df.round(4)


print("Original:")
results_df



Original:


,Model,Accuracy,Sensitivity,Specificity,AUC,F1
0,RNN_SetA,0.5438,0.5128,0.640,0.6169,0.6140
1,RNN_SetB,0.5258,0.5115,0.570,0.5350,0.6068
2,RNN_SetC,0.5261,0.4865,0.640,0.5377,0.5905
3,DNN_SetA,0.5722,0.5910,0.505,0.6078,0.6673
4,DNN_SetB,0.5497,0.5827,0.455,0.5042,0.6422
5,DNN_SetC,0.6193,0.6122,0.620,0.5772,0.6884
6,LSTM_SetA,0.4967,0.4705,0.570,0.5812,0.5691
7,LSTM_SetB,0.3856,0.2321,0.810,0.5617,0.3482
8,LSTM_SetC,0.4268,0.3115,0.745,0.5449,0.4276
9,StackedLSTM_SetA,0.5961,0.6218,0.525,0.6078,0.6817


In [ ]:
#Results by AUC

results_dfAUC=results_df.copy()

results_dfAUC=results_dfAUC.sort_values(by="AUC", ascending=False)

print("\nSorted by AUC (descending):")
results_dfAUC


Sorted by AUC (descending):


,Model,Accuracy,Sensitivity,Specificity,AUC,F1
0,RNN_SetA,0.5438,0.5128,0.640,0.6169,0.6140
12,biLSTM_SetA,0.5958,0.6224,0.520,0.6160,0.6861
9,StackedLSTM_SetA,0.5961,0.6218,0.525,0.6078,0.6817
3,DNN_SetA,0.5722,0.5910,0.505,0.6078,0.6673
14,biLSTM_SetC,0.5722,0.5641,0.585,0.6031,0.6521
6,LSTM_SetA,0.4967,0.4705,0.570,0.5812,0.5691
5,DNN_SetC,0.6193,0.6122,0.620,0.5772,0.6884
13,biLSTM_SetB,0.5784,0.5962,0.520,0.5768,0.6556
10,StackedLSTM_SetB,0.5435,0.5103,0.635,0.5695,0.6098
7,LSTM_SetB,0.3856,0.2321,0.810,0.5617,0.3482


#Hyperparameter Tuning

**The top three models were selected based on AUC from the baseline comparison results:**


**Top 3 Models: StackedLSTM_SetA, DNN_SetA, biGRU_SetA:**

In [ ]:
import random
from tensorflow.keras.optimizers import Adam


In [ ]:
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)


**Building Models**

*   Blueprint for each model type




In [ ]:
#BiLSTM

def build_biLSTM_tuned(n_features, units1, units2, learning_rate):
    model = Sequential([
        Bidirectional(LSTM(units1, return_sequences=True), input_shape=(1, n_features)),
        Bidirectional(LSTM(units2)),
        Dense(1, activation="sigmoid")
    ])

    model.compile(
        optimizer=Adam(learning_rate=learning_rate),
        loss="binary_crossentropy",
        metrics=["accuracy"]
    )

    return model



**Evaluation**

In [ ]:
def evaluate_tuned_model(model_name, build_fn, X_data, y_data,
                         sequence_model=False,
                         epochs=20, batch_size=16,
                         **build_kwargs):

    acc_list = []
    recall_list = []
    spec_list = []
    auc_list = []
    f1_list = []

    start_time = time.time()

    for fold_i, (train_rows, test_rows) in enumerate(skf.split(X_data, y_data), start=1):

        # Split
        X_train, X_test = X_data[train_rows], X_data[test_rows]
        y_train, y_test = y_data[train_rows], y_data[test_rows]

        # Scale inside each fold
        scaler = StandardScaler()
        X_train = scaler.fit_transform(X_train)
        X_test = scaler.transform(X_test)

        # Reshape only for sequence models
        if sequence_model:
            X_train = X_train.reshape((X_train.shape[0], 1, X_train.shape[1]))
            X_test = X_test.reshape((X_test.shape[0], 1, X_test.shape[1]))
            n_features = X_train.shape[2]
        else:
            n_features = X_train.shape[1]

        # Build model using sampled hyperparameters
        model = build_fn(n_features, **build_kwargs)

        # Train
        model.fit(
            X_train, y_train,
            epochs=epochs,
            batch_size=batch_size,
            verbose=0
        )

        # Predict
        y_prob = model.predict(X_test, verbose=0).ravel()
        y_pred = (y_prob >= 0.7).astype(int)

        # Confusion matrix
        tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

        # Metrics
        acc_list.append(accuracy_score(y_test, y_pred))
        recall_list.append(recall_score(y_test, y_pred, zero_division=0))
        f1_list.append(f1_score(y_test, y_pred, zero_division=0))
        auc_list.append(roc_auc_score(y_test, y_prob))
        spec_list.append(tn / (tn + fp) if (tn + fp) > 0 else 0)

        # cleanup
        del model, X_train, X_test, y_train, y_test, y_prob, y_pred
        K.clear_session()
        gc.collect()

    runtime = time.time() - start_time

    return {
        "Model": model_name,
        "Accuracy": np.mean(acc_list),
        "Sensitivity": np.mean(recall_list),
        "Specificity": np.mean(spec_list),
        "AUC": np.mean(auc_list),
        "F1": np.mean(f1_list)
    }

**Random** **Search**

In [ ]:
#def random_search_tuning(model_name, build_fn, X_data, y_data,
                         #param_dist, n_iter=10, sequence_model=False):

    #tuning_results = []

    #for i in range(n_iter):
        # Randomly choose one value for each hyperparameter
       # params = {k: random.choice(v) for k, v in param_dist.items()}

        # Evaluate that one sampled combination
        #result = evaluate_tuned_model(
            #model_name=f"{model_name}_tuned_{i+1}",
            #build_fn=build_fn,
            #X_data=X_data,
            #y_data=y_data,
            #sequence_model=sequence_model,
            #epochs=params["epochs"],
            #batch_size=params["batch_size"],
            #**{k: v for k, v in params.items() if k not in ["epochs", "batch_size"]}
        #)

        #tuning_results.append(result)

        #gc.collect()
        #K.clear_session()

    # Convert all tuning results into a dataframe
    #tuning_df = pd.DataFrame(tuning_results).round(4)

    # Sort by AUC from highest to lowest
    #tuning_df = tuning_df.sort_values(by="AUC", ascending=False).reset_index(drop=True)

    #return tuning_df

In [ ]:
def random_search_tuning(model_name, build_fn, X_data, y_data,
                         param_dist, n_iter=10, sequence_model=False):

    tuning_results = []

    for i in range(n_iter):
        # 1. Randomly sample hyperparameters
        params = {k: random.choice(v) for k, v in param_dist.items()}

        # 2. Train & evaluate model
        result = evaluate_tuned_model(
            model_name=f"{model_name}_tuned_{i+1}",
            build_fn=build_fn,
            X_data=X_data,
            y_data=y_data,
            sequence_model=sequence_model,
            epochs=params["epochs"],
            batch_size=params["batch_size"],
            **{k: v for k, v in params.items() if k not in ["epochs", "batch_size"]}
        )

        # 3. Add hyperparameters into results
        result["units1"] = params["units1"]
        result["units2"] = params["units2"]
        result["learning_rate"] = params["learning_rate"]
        result["epochs"] = params["epochs"]
        result["batch_size"] = params["batch_size"]

        # 4. Save result
        tuning_results.append(result)

    # 5. Convert to DataFrame
    tuning_df = pd.DataFrame(tuning_results)

    return tuning_df

**Parameters**

In [ ]:
#BiLSTM hyperparameters
bilstm_param_dist = {
    "units1": [8, 16, 32],
    "units2": [4, 8, 16],
    "learning_rate": [0.001, 0.0005],
    "epochs": [10, 20],
    "batch_size": [16, 32]
}


**Run Tuning**

In [ ]:
#biLSTM
bilstm_tuning_df = random_search_tuning(
    model_name="biLSTM_SetA",
    build_fn=build_biLSTM_tuned,
    X_data=X,
    y_data=y,
    param_dist=bilstm_param_dist,
    n_iter=5,
    sequence_model=True
)

print("biLSTM tuning results:")
print(bilstm_tuning_df)


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `

biLSTM tuning results:
                 Model  Accuracy  Sensitivity  Specificity       AUC   F1  \
0  biLSTM_SetA_tuned_1  0.268954          0.0          1.0  0.569615  0.0   
1  biLSTM_SetA_tuned_2  0.268954          0.0          1.0  0.577821  0.0   
2  biLSTM_SetA_tuned_3  0.268954          0.0          1.0  0.559487  0.0   
3  biLSTM_SetA_tuned_4  0.268954          0.0          1.0  0.484744  0.0   
4  biLSTM_SetA_tuned_5  0.268954          0.0          1.0  0.541154  0.0   

   units1  units2  learning_rate  epochs  batch_size  
0      16       8         0.0010      10          32  
1      32       4         0.0005      10          32  
2      16      16         0.0005      10          16  
3       8       4         0.0005      20          32  
4       8      16         0.0005      10          32  


##Model Comparison

In [ ]:
# Sort by AUC (best at top)
bilstm_tuning_df = bilstm_tuning_df.sort_values(
    by="AUC", ascending=False
).reset_index(drop=True)

print("\nbiLSTM tuning results (sorted by AUC):")
print(bilstm_tuning_df)

# Best Model
best_model = bilstm_tuning_df.iloc[0]

print("\nBest overall biLSTM model:")
print(best_model)

# Clean comparison table
print("\nClean comparison table:")
print(bilstm_tuning_df[[
    "Model", "AUC", "Accuracy", "F1", "Sensitivity", "Specificity"
]])


biLSTM tuning results (sorted by AUC):
                 Model  Accuracy  Sensitivity  Specificity       AUC   F1  \
0  biLSTM_SetA_tuned_2  0.268954          0.0          1.0  0.577821  0.0   
1  biLSTM_SetA_tuned_1  0.268954          0.0          1.0  0.569615  0.0   
2  biLSTM_SetA_tuned_3  0.268954          0.0          1.0  0.559487  0.0   
3  biLSTM_SetA_tuned_5  0.268954          0.0          1.0  0.541154  0.0   
4  biLSTM_SetA_tuned_4  0.268954          0.0          1.0  0.484744  0.0   

   units1  units2  learning_rate  epochs  batch_size  
0      32       4         0.0005      10          32  
1      16       8         0.0010      10          32  
2      16      16         0.0005      10          16  
3       8      16         0.0005      10          32  
4       8       4         0.0005      20          32  

Best overall biLSTM model:
Model            biLSTM_SetA_tuned_2
Accuracy                    0.268954
Sensitivity                      0.0
Specificity                 

In [ ]:
best_models_df = pd.DataFrame([
    bilstm_tuning_df.iloc[0],
])

best_models_df = best_models_df.sort_values(by="AUC", ascending=False).reset_index(drop=True)

best_models_df



,Model,Accuracy,Sensitivity,Specificity,AUC,F1,units1,units2,learning_rate,epochs,batch_size
0,biLSTM_SetA_tuned_1,0.268954,0.0,1.0,0.569615,0.0,16,8,0.001,10,32


In [ ]:
print("\nClean comparison table:")
print(bilstm_tuning_df[[
    "Model", "AUC", "Accuracy", "F1", "Sensitivity", "Specificity",
    "units1", "units2", "learning_rate", "epochs", "batch_size"
]])


Clean comparison table:
                 Model       AUC  Accuracy   F1  Sensitivity  Specificity  \
0  biLSTM_SetA_tuned_2  0.577821  0.268954  0.0          0.0          1.0   
1  biLSTM_SetA_tuned_1  0.569615  0.268954  0.0          0.0          1.0   
2  biLSTM_SetA_tuned_3  0.559487  0.268954  0.0          0.0          1.0   
3  biLSTM_SetA_tuned_5  0.541154  0.268954  0.0          0.0          1.0   
4  biLSTM_SetA_tuned_4  0.484744  0.268954  0.0          0.0          1.0   

   units1  units2  learning_rate  epochs  batch_size  
0      32       4         0.0005      10          32  
1      16       8         0.0010      10          32  
2      16      16         0.0005      10          16  
3       8      16         0.0005      10          32  
4       8       4         0.0005      20          32  
